### ISSUE TITLE
Virtuoso image is outdated?

### ISSUE THREAD

**Issue by gannebamm** [CunliangGeng/fairdatapoint-service#2] opened 2021-03-16 13:38 UTC
Hi,

See https://github.com/fair-data/fairdatapoint-service/blob/master/docker-compose.yml#L19

This will pull https://hub.docker.com/r/tenforce/virtuoso/

which is 2 years old and does seem to be abandoned.

**Comment by CunliangGeng** [comment] 2021-03-16 15:21
Thanks for pointing it out. 

It's the latest version even though it's 2 years old. See the releases of the source code https://github.com/openlink/virtuoso-opensource/releases.

**Comment by gannebamm** [comment] 2021-03-17 09:26
> It's the latest version

True. I do not use the fairdatapoint repo and just took a look for our RDM, but I must say relying on a 2-year-old and seemingly abandoned backend will block us from using the (maybe very good) fairdatapoint. I do not want to be that guy, but I think if you want to deliver the project to more users you should discuss if other more maintained backend options are viable.

**Comment by LourensVeen** [comment] 2021-03-17 09:34
I'd like to just chime in here to point out that the issue isn't so much whether it is the latest version of Virtuoso (if it works it works, and I assume it's not directly accessible from the outside world?), but that there's a bunch of other stuff in that image that hasn't had a security update in two years. If Openlink don't provide something newer, maybe we can at least rebuild the image?

**Comment by CunliangGeng** [comment] 2021-03-22 15:31
Hi @gannebamm, thank you for your comments.

We replaced the [tenforce/virtuoso](https://hub.docker.com/repository/docker/nlesc/virtuoso) with the [nlesc/virtuoso](https://hub.docker.com/repository/docker/nlesc/virtuoso) that was built by us on [latest commit of the open source code](https://github.com/fair-data/virtuoso-opensource).  Details see PR #3.

This issue will be closed in one week if you have no further remarks. Thanks.

**Closed as completed** 2021-03-26 09:32 UTC
